# Automação Web e Busca de Informações com Python

#### Desafio: 

Trabalhamos em uma importadora e o preço dos nossos produtos é vinculado a cotação de:
- Dólar
- Euro
- Ouro

Precisamos pegar na internet, de forma automática, a cotação desses 3 itens e saber quanto devemos cobrar pelos nossos produtos, considerando uma margem de contribuição que temos na nossa base de dados.

Base de Dados: https://drive.google.com/drive/folders/1KmAdo593nD8J9QBaZxPOG1yxHZua4Rtv?usp=sharing

Para isso, vamos criar uma automação web:

- Usaremos o selenium
- Importante: baixar o webdriver

In [37]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (4.3.0)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: async-generator>=1.9 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sortedcontainers in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: cffi>=1.14 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (37.0.4)
Requirement already satisfied: certifi in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2022.6.15)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (22.0.0)
Requirement already satisfied: pycparser in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\rafae\anaconda3\envs\teste\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [38]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# passo 1: pegar cotação dólar
# abrir o navegador
nav=webdriver.Chrome()

# entrar no google
nav.get('https://www.google.com/')

# pesquisar cotação
nav.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação dolar')
nav.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

# pegar a cotação
cot_dol=nav.find_element('xpath','//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cot_dol)

# passo 2: pegar cotação euro
nav.get('https://www.google.com/')
nav.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação euro')
nav.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
cot_euro=nav.find_element('xpath','//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cot_euro)


# passo 3: pegar cotação ouro
nav.get('https://www.melhorcambio.com/ouro-hoje#:~:text=O%20valor%20do%20grama%20do,em%20R%24%20293%2C35.')
cot_ouro=nav.find_element('xpath','//*[@id="comercial"]').get_attribute('value')
cot_ouro=cot_ouro.replace(',', '.')
print(cot_ouro)

nav.quit()

5.160299999999999
5.2589999999999995
291.07

### Agora vamos atualiza a nossa base de preços com as novas cotações

- Importando a base de dados

In [39]:
# passo 4: atualizar a base de dados
import pandas as pd
tab=pd.read_excel('Produtos.xlsx')
display(tab)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

- Atualizando os preços e o cálculo do Preço Final

In [40]:
# passo 5: recalcular os preços
# atualizar as cotações
tab.loc[tab['Moeda']=='Dólar', 'Cotação'] = float(cot_dol)
tab.loc[tab['Moeda']=='Euro', 'Cotação'] = float(cot_euro)
tab.loc[tab['Moeda']=='Ouro', 'Cotação'] = float(cot_ouro)

# preço de compra = preço original * cotação
tab['Preço de Compra'] = tab['Preço Original'] * tab['Cotação']

# preço de venda = preço de compra * margem
tab['Preço de Venda'] = tab['Preço de Compra'] * tab['Margem']

display(tab)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.1603,5160.248397,1.40,7224.347756
1,Carro Renault,4500.00,Euro,5.2590,23665.500000,2.00,47331.000000
2,Notebook Dell,899.99,Dólar,5.1603,4644.218397,1.70,7895.171275
3,IPhone,799.00,Dólar,5.1603,4123.079700,1.70,7009.235490
4,Carro Fiat,3000.00,Euro,5.2590,15777.000000,1.90,29976.300000
5,Celular Xiaomi,480.48,Dólar,5.1603,2479.420944,2.00,4958.841888
6,Joia 20g,20.00,Ouro,291.0700,5821.400000,1.15,6694.610000

### Agora vamos exportar a nova base de preços atualizada

In [41]:
# passo 6: exportar a base de dados
tab.to_excel('Produtos Novo.xlsx', index=False)